// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class BgpAggregationWriter
{
    protected BgpAggregationWriter(int offset) { this.offset = offset; }
    protected int offset;
}