// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class BgpMultipathWriter
{
    protected BgpMultipathWriter(int offset) { this.offset = offset; }
    protected int offset;
}