// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class BgpMultipathReader
{
    protected BgpMultipathReader(ddlog.__routing.BgpMultipath inner) { this.inner = inner; }
    private ddlog.__routing.BgpMultipath inner;
    public vnode_tReader node ()
    {
        return new vnode_tReader(this.inner.node());
    }
    public long k ()
    {
        return (long)this.inner.k();
    }
    public boolean relax ()
    {
        return this.inner.relax();
    }
}