// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class BgpNetworkReader
{
    protected BgpNetworkReader(ddlog.__routing.BgpNetwork inner) { this.inner = inner; }
    private ddlog.__routing.BgpNetwork inner;
    public vnode_tReader node ()
    {
        return new vnode_tReader(this.inner.node());
    }
    public prefix_tReader prefix ()
    {
        return new prefix_tReader(this.inner.prefix());
    }
}