// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class BgpNetworkWriter
{
    protected BgpNetworkWriter(int offset) { this.offset = offset; }
    protected int offset;
}