// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class BgpNeighborWriter
{
    protected BgpNeighborWriter(int offset) { this.offset = offset; }
    protected int offset;
}