// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class BgpRedisWriter
{
    protected BgpRedisWriter(int offset) { this.offset = offset; }
    protected int offset;
}