// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class BgpReflectClientWriter
{
    protected BgpReflectClientWriter(int offset) { this.offset = offset; }
    protected int offset;
}