// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class community_tReader
{
    protected community_tReader(ddlog.__routing.community_t inner) { this.inner = inner; }
    private ddlog.__routing.community_t inner;
    public String as_ ()
    {
        return this.inner.as_();
    }
    public String tag ()
    {
        return this.inner.tag();
    }
}