// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class community_tWriter
{
    protected community_tWriter(int offset) { this.offset = offset; }
    protected int offset;
}