// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class FibReader
{
    protected FibReader(ddlog.__routing.Fib inner) { this.inner = inner; }
    private ddlog.__routing.Fib inner;
    public String node ()
    {
        return this.inner.node();
    }
    public String prefix ()
    {
        return this.inner.prefix();
    }
    public String intf ()
    {
        return this.inner.intf();
    }
    public String next_hop_ip ()
    {
        return this.inner.nextHopIp();
    }
}