// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class IBgpNeighborWriter
{
    protected IBgpNeighborWriter(int offset) { this.offset = offset; }
    protected int offset;
}