// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class InterfaceWriter
{
    protected InterfaceWriter(int offset) { this.offset = offset; }
    protected int offset;
}