// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class InterfaceReader
{
    protected InterfaceReader(ddlog.__routing.Interface inner) { this.inner = inner; }
    private ddlog.__routing.Interface inner;
    public vnode_tReader node ()
    {
        return new vnode_tReader(this.inner.node());
    }
    public String intf ()
    {
        return this.inner.intf();
    }
    public prefix_tReader prefix ()
    {
        return new prefix_tReader(this.inner.prefix());
    }
}