// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class ip_tReader
{
    protected ip_tReader(ddlog.__routing.ip_t inner) { this.inner = inner; }
    private ddlog.__routing.ip_t inner;
    public int b3 ()
    {
        return (int)this.inner.b3();
    }
    public int b2 ()
    {
        return (int)this.inner.b2();
    }
    public int b1 ()
    {
        return (int)this.inner.b1();
    }
    public int b0 ()
    {
        return (int)this.inner.b0();
    }
}