// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class L3LinkReader
{
    protected L3LinkReader(ddlog.__routing.L3Link inner) { this.inner = inner; }
    private ddlog.__routing.L3Link inner;
    public String node1 ()
    {
        return this.inner.node1();
    }
    public String int1 ()
    {
        return this.inner.int1();
    }
    public String node2 ()
    {
        return this.inner.node2();
    }
    public String int2 ()
    {
        return this.inner.int2();
    }
}