// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public class match_attr_tReader
{
    protected static match_attr_tReader init(byte type, java.util.function.UnaryOperator<Table> inner)
    {
        switch (type)
        {
            case ddlog.__routing.match_attr_t.MatchNextHopIp: return new MatchNextHopIp((ddlog.__routing.MatchNextHopIp) inner.apply(new ddlog.__routing.MatchNextHopIp()));
            case ddlog.__routing.match_attr_t.MatchPrefixList: return new MatchPrefixList((ddlog.__routing.MatchPrefixList) inner.apply(new ddlog.__routing.MatchPrefixList()));
            case ddlog.__routing.match_attr_t.MatchAsPath: return new MatchAsPath((ddlog.__routing.MatchAsPath) inner.apply(new ddlog.__routing.MatchAsPath()));
            case ddlog.__routing.match_attr_t.MatchCommunity: return new MatchCommunity((ddlog.__routing.MatchCommunity) inner.apply(new ddlog.__routing.MatchCommunity()));
        }
        throw new RuntimeException("Invalid type " + type + " in match_attr_tReader");
    }
    public static final class MatchNextHopIp extends match_attr_tReader
    {
        protected MatchNextHopIp(ddlog.__routing.MatchNextHopIp inner) { this.inner = inner; }
        private ddlog.__routing.MatchNextHopIp inner;
        public ip_tReader next_hop_ip ()
        {
            return new ip_tReader(this.inner.nextHopIp());
        }
    }
    public static final class MatchPrefixList extends match_attr_tReader
    {
        protected MatchPrefixList(ddlog.__routing.MatchPrefixList inner) { this.inner = inner; }
        private ddlog.__routing.MatchPrefixList inner;
        public java.util.List<prefix_list_tReader> prefix_list ()
        {
            return ((java.util.function.Supplier<java.util.List<prefix_list_tReader>>) (() ->
                   {
                       int len0 = this.inner.prefixListLength();
                       java.util.List<prefix_list_tReader> lst0 = new java.util.ArrayList<prefix_list_tReader>(len0);
                       for (int i0 = 0; i0 < len0; i0++)
                       {
                           ddlog.__routing.__Table_prefix_list_t x0 = this.inner.prefixList(i0);
                           lst0.add(prefix_list_tReader.init(x0.vType(), (Table __t2) -> x0.v(__t2)));
                       }
                       return lst0;
                   })).get();
        }
    }
    public static final class MatchAsPath extends match_attr_tReader
    {
        protected MatchAsPath(ddlog.__routing.MatchAsPath inner) { this.inner = inner; }
        private ddlog.__routing.MatchAsPath inner;
        public long as_ ()
        {
            return (long)this.inner.as_();
        }
    }
    public static final class MatchCommunity extends match_attr_tReader
    {
        protected MatchCommunity(ddlog.__routing.MatchCommunity inner) { this.inner = inner; }
        private ddlog.__routing.MatchCommunity inner;
        public community_tReader community ()
        {
            return new community_tReader(this.inner.community());
        }
    }
}