// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class match_attr_tWriter
{
    protected match_attr_tWriter(byte type, int offset) { this.type = type; this.offset = offset; }
    protected byte type;
    protected int offset;
}