// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class OspfMultipathWriter
{
    protected OspfMultipathWriter(int offset) { this.offset = offset; }
    protected int offset;
}