// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class OspfRedisWriter
{
    protected OspfRedisWriter(int offset) { this.offset = offset; }
    protected int offset;
}