// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class OspfMultipathReader
{
    protected OspfMultipathReader(ddlog.__routing.OspfMultipath inner) { this.inner = inner; }
    private ddlog.__routing.OspfMultipath inner;
    public vnode_tReader node ()
    {
        return new vnode_tReader(this.inner.node());
    }
    public long k ()
    {
        return (long)this.inner.k();
    }
    public long process ()
    {
        return (long)this.inner.process();
    }
}