// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class OspfStubAreaReader
{
    protected OspfStubAreaReader(ddlog.__routing.OspfStubArea inner) { this.inner = inner; }
    private ddlog.__routing.OspfStubArea inner;
    public vnode_tReader node ()
    {
        return new vnode_tReader(this.inner.node());
    }
    public long process ()
    {
        return (long)this.inner.process();
    }
    public long area ()
    {
        return (long)this.inner.area();
    }
    public boolean no_summary ()
    {
        return this.inner.noSummary();
    }
    public boolean default_originate ()
    {
        return this.inner.defaultOriginate();
    }
    public boolean no_redis ()
    {
        return this.inner.noRedis();
    }
    public long metric ()
    {
        return (long)this.inner.metric();
    }
}