// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class OspfStubAreaWriter
{
    protected OspfStubAreaWriter(int offset) { this.offset = offset; }
    protected int offset;
}