// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class prefix_tWriter
{
    protected prefix_tWriter(int offset) { this.offset = offset; }
    protected int offset;
}