// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class prefix_list_tWriter
{
    protected prefix_list_tWriter(byte type, int offset) { this.type = type; this.offset = offset; }
    protected byte type;
    protected int offset;
}