// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public class prefix_list_tReader
{
    protected static prefix_list_tReader init(byte type, java.util.function.UnaryOperator<Table> inner)
    {
        switch (type)
        {
            case ddlog.__routing.prefix_list_t.CommonPrefix: return new CommonPrefix((ddlog.__routing.CommonPrefix) inner.apply(new ddlog.__routing.CommonPrefix()));
            case ddlog.__routing.prefix_list_t.ExtendPrefix: return new ExtendPrefix((ddlog.__routing.ExtendPrefix) inner.apply(new ddlog.__routing.ExtendPrefix()));
        }
        throw new RuntimeException("Invalid type " + type + " in prefix_list_tReader");
    }
    public static final class CommonPrefix extends prefix_list_tReader
    {
        protected CommonPrefix(ddlog.__routing.CommonPrefix inner) { this.inner = inner; }
        private ddlog.__routing.CommonPrefix inner;
        public prefix_tReader prefix ()
        {
            return new prefix_tReader(this.inner.prefix());
        }
    }
    public static final class ExtendPrefix extends prefix_list_tReader
    {
        protected ExtendPrefix(ddlog.__routing.ExtendPrefix inner) { this.inner = inner; }
        private ddlog.__routing.ExtendPrefix inner;
        public prefix_tReader prefix ()
        {
            return new prefix_tReader(this.inner.prefix());
        }
        public long ge ()
        {
            return (long)this.inner.ge();
        }
        public long le ()
        {
            return (long)this.inner.le();
        }
    }
}