// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class prefix_tReader
{
    protected prefix_tReader(ddlog.__routing.prefix_t inner) { this.inner = inner; }
    private ddlog.__routing.prefix_t inner;
    public ip_tReader addr ()
    {
        return new ip_tReader(this.inner.addr());
    }
    public ip_tReader mask ()
    {
        return new ip_tReader(this.inner.mask());
    }
}