// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class RouteMapOutWriter
{
    protected RouteMapOutWriter(int offset) { this.offset = offset; }
    protected int offset;
}