// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class routingRelation
{
    public static final int BgpAggregation = 7;
    public static final int BgpMultipath = 8;
    public static final int BgpNeighbor = 10;
    public static final int BgpNetwork = 11;
    public static final int BgpRedis = 12;
    public static final int BgpReflectClient = 13;
    public static final int Fib = 16;
    public static final int IBgpNeighbor = 18;
    public static final int Interface = 19;
    public static final int L3Link = 21;
    public static final int Node = 28;
    public static final int OspfIntfSetting = 30;
    public static final int OspfMultipath = 31;
    public static final int OspfRedis = 34;
    public static final int OspfStubArea = 37;
    public static final int RouteMapIn = 38;
    public static final int RouteMapOut = 39;
    public static final int StaticRoute = 41;
}