// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class route_map_tReader
{
    protected route_map_tReader(ddlog.__routing.route_map_t inner) { this.inner = inner; }
    private ddlog.__routing.route_map_t inner;
    public boolean permit ()
    {
        return this.inner.permit();
    }
    public java.util.List<match_attr_tReader> match_condition ()
    {
        return ((java.util.function.Supplier<java.util.List<match_attr_tReader>>) (() ->
               {
                   int len0 = this.inner.matchConditionLength();
                   java.util.List<match_attr_tReader> lst0 = new java.util.ArrayList<match_attr_tReader>(len0);
                   for (int i0 = 0; i0 < len0; i0++)
                   {
                       ddlog.__routing.__Table_match_attr_t x0 = this.inner.matchCondition(i0);
                       lst0.add(match_attr_tReader.init(x0.vType(), (Table __t2) -> x0.v(__t2)));
                   }
                   return lst0;
               })).get();
    }
    public java.util.List<set_attr_tReader> set_action ()
    {
        return ((java.util.function.Supplier<java.util.List<set_attr_tReader>>) (() ->
               {
                   int len0 = this.inner.setActionLength();
                   java.util.List<set_attr_tReader> lst0 = new java.util.ArrayList<set_attr_tReader>(len0);
                   for (int i0 = 0; i0 < len0; i0++)
                   {
                       ddlog.__routing.__Table_set_attr_t x0 = this.inner.setAction(i0);
                       lst0.add(set_attr_tReader.init(x0.vType(), (Table __t2) -> x0.v(__t2)));
                   }
                   return lst0;
               })).get();
    }
}