// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class RouteMapInWriter
{
    protected RouteMapInWriter(int offset) { this.offset = offset; }
    protected int offset;
}