// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class RouteMapOutReader
{
    protected RouteMapOutReader(ddlog.__routing.RouteMapOut inner) { this.inner = inner; }
    private ddlog.__routing.RouteMapOut inner;
    public vnode_tReader node ()
    {
        return new vnode_tReader(this.inner.node());
    }
    public vnode_tReader to_node ()
    {
        return new vnode_tReader(this.inner.toNode());
    }
    public java.util.List<route_map_tReader> policy ()
    {
        return ((java.util.function.Supplier<java.util.List<route_map_tReader>>) (() ->
               {
                   int len0 = this.inner.policyLength();
                   java.util.List<route_map_tReader> lst0 = new java.util.ArrayList<route_map_tReader>(len0);
                   for (int i0 = 0; i0 < len0; i0++)
                   {
                       ddlog.__routing.route_map_t x0 = this.inner.policy(i0);
                       lst0.add(new route_map_tReader(x0));
                   }
                   return lst0;
               })).get();
    }
}