// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class route_map_tWriter
{
    protected route_map_tWriter(int offset) { this.offset = offset; }
    protected int offset;
}