// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public class set_attr_tReader
{
    protected static set_attr_tReader init(byte type, java.util.function.UnaryOperator<Table> inner)
    {
        switch (type)
        {
            case ddlog.__routing.set_attr_t.SetNextHopIp: return new SetNextHopIp((ddlog.__routing.SetNextHopIp) inner.apply(new ddlog.__routing.SetNextHopIp()));
            case ddlog.__routing.set_attr_t.SetLocalPref: return new SetLocalPref((ddlog.__routing.SetLocalPref) inner.apply(new ddlog.__routing.SetLocalPref()));
            case ddlog.__routing.set_attr_t.SetMed: return new SetMed((ddlog.__routing.SetMed) inner.apply(new ddlog.__routing.SetMed()));
            case ddlog.__routing.set_attr_t.SetCommunity: return new SetCommunity((ddlog.__routing.SetCommunity) inner.apply(new ddlog.__routing.SetCommunity()));
        }
        throw new RuntimeException("Invalid type " + type + " in set_attr_tReader");
    }
    public static final class SetNextHopIp extends set_attr_tReader
    {
        protected SetNextHopIp(ddlog.__routing.SetNextHopIp inner) { this.inner = inner; }
        private ddlog.__routing.SetNextHopIp inner;
        public ip_tReader next_hop_ip ()
        {
            return new ip_tReader(this.inner.nextHopIp());
        }
    }
    public static final class SetLocalPref extends set_attr_tReader
    {
        protected SetLocalPref(ddlog.__routing.SetLocalPref inner) { this.inner = inner; }
        private ddlog.__routing.SetLocalPref inner;
        public long local_pref ()
        {
            return (long)this.inner.localPref();
        }
    }
    public static final class SetMed extends set_attr_tReader
    {
        protected SetMed(ddlog.__routing.SetMed inner) { this.inner = inner; }
        private ddlog.__routing.SetMed inner;
        public long med ()
        {
            return (long)this.inner.med();
        }
    }
    public static final class SetCommunity extends set_attr_tReader
    {
        protected SetCommunity(ddlog.__routing.SetCommunity inner) { this.inner = inner; }
        private ddlog.__routing.SetCommunity inner;
        public boolean additive ()
        {
            return this.inner.additive();
        }
        public community_tReader community ()
        {
            return new community_tReader(this.inner.community());
        }
    }
}