// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class StaticRouteReader
{
    protected StaticRouteReader(ddlog.__routing.StaticRoute inner) { this.inner = inner; }
    private ddlog.__routing.StaticRoute inner;
    public vnode_tReader node ()
    {
        return new vnode_tReader(this.inner.node());
    }
    public prefix_tReader prefix ()
    {
        return new prefix_tReader(this.inner.prefix());
    }
    public ip_tReader next_hop_ip ()
    {
        return new ip_tReader(this.inner.nextHopIp());
    }
    public long adminCost ()
    {
        return (long)this.inner.adminCost();
    }
}