// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class StaticRouteWriter
{
    protected StaticRouteWriter(int offset) { this.offset = offset; }
    protected int offset;
}