// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class Tuple0Reader
{
    protected Tuple0Reader(ddlog.__routing.Tuple0 inner) { this.inner = inner; }
    private ddlog.__routing.Tuple0 inner;
}