// Automatically generated by the DDlog compiler.
package ddlog.routing;
public final class vnode_tWriter
{
    protected vnode_tWriter(int offset) { this.offset = offset; }
    protected int offset;
}