// Automatically generated by the DDlog compiler.
package ddlog.routing;
import com.google.flatbuffers.*;
public final class vnode_tReader
{
    protected vnode_tReader(ddlog.__routing.vnode_t inner) { this.inner = inner; }
    private ddlog.__routing.vnode_t inner;
    public String device ()
    {
        return this.inner.device();
    }
    public String vrf ()
    {
        return this.inner.vrf();
    }
}