// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class __Command extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static __Command getRootAs__Command(ByteBuffer _bb) { return getRootAs__Command(_bb, new __Command()); }
  public static __Command getRootAs__Command(ByteBuffer _bb, __Command obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public __Command __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte operation() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long weight() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long relid() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 7L; }
  public byte valType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table val(Table obj) { int o = __offset(12); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int create__Command(FlatBufferBuilder builder,
      byte operation,
      long weight,
      long relid,
      byte val_type,
      int valOffset) {
    builder.startTable(5);
    __Command.addRelid(builder, relid);
    __Command.addWeight(builder, weight);
    __Command.addVal(builder, valOffset);
    __Command.addValType(builder, val_type);
    __Command.addOperation(builder, operation);
    return __Command.end__Command(builder);
  }

  public static void start__Command(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addOperation(FlatBufferBuilder builder, byte operation) { builder.addByte(0, operation, 0); }
  public static void addWeight(FlatBufferBuilder builder, long weight) { builder.addLong(1, weight, 0L); }
  public static void addRelid(FlatBufferBuilder builder, long relid) { builder.addLong(2, relid, 7L); }
  public static void addValType(FlatBufferBuilder builder, byte valType) { builder.addByte(3, valType, 0); }
  public static void addVal(FlatBufferBuilder builder, int valOffset) { builder.addOffset(4, valOffset, 0); }
  public static int end__Command(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public __Command get(int j) { return get(new __Command(), j); }
    public __Command get(__Command obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

