// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class __Commands extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static __Commands getRootAs__Commands(ByteBuffer _bb) { return getRootAs__Commands(_bb, new __Commands()); }
  public static __Commands getRootAs__Commands(ByteBuffer _bb, __Commands obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public __Commands __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.__Command commands(int j) { return commands(new ddlog.__routing.__Command(), j); }
  public ddlog.__routing.__Command commands(ddlog.__routing.__Command obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int commandsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ddlog.__routing.__Command.Vector commandsVector() { return commandsVector(new ddlog.__routing.__Command.Vector()); }
  public ddlog.__routing.__Command.Vector commandsVector(ddlog.__routing.__Command.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int create__Commands(FlatBufferBuilder builder,
      int commandsOffset) {
    builder.startTable(1);
    __Commands.addCommands(builder, commandsOffset);
    return __Commands.end__Commands(builder);
  }

  public static void start__Commands(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addCommands(FlatBufferBuilder builder, int commandsOffset) { builder.addOffset(0, commandsOffset, 0); }
  public static int createCommandsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCommandsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int end__Commands(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finish__CommandsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixed__CommandsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public __Commands get(int j) { return get(new __Commands(), j); }
    public __Commands get(__Commands obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

