// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class __Table_Vec_set_attr_t extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static __Table_Vec_set_attr_t getRootAs__Table_Vec_set_attr_t(ByteBuffer _bb) { return getRootAs__Table_Vec_set_attr_t(_bb, new __Table_Vec_set_attr_t()); }
  public static __Table_Vec_set_attr_t getRootAs__Table_Vec_set_attr_t(ByteBuffer _bb, __Table_Vec_set_attr_t obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public __Table_Vec_set_attr_t __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.__Table_set_attr_t v(int j) { return v(new ddlog.__routing.__Table_set_attr_t(), j); }
  public ddlog.__routing.__Table_set_attr_t v(ddlog.__routing.__Table_set_attr_t obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int vLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ddlog.__routing.__Table_set_attr_t.Vector vVector() { return vVector(new ddlog.__routing.__Table_set_attr_t.Vector()); }
  public ddlog.__routing.__Table_set_attr_t.Vector vVector(ddlog.__routing.__Table_set_attr_t.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int create__Table_Vec_set_attr_t(FlatBufferBuilder builder,
      int vOffset) {
    builder.startTable(1);
    __Table_Vec_set_attr_t.addV(builder, vOffset);
    return __Table_Vec_set_attr_t.end__Table_Vec_set_attr_t(builder);
  }

  public static void start__Table_Vec_set_attr_t(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addV(FlatBufferBuilder builder, int vOffset) { builder.addOffset(0, vOffset, 0); }
  public static int createVVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startVVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int end__Table_Vec_set_attr_t(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public __Table_Vec_set_attr_t get(int j) { return get(new __Table_Vec_set_attr_t(), j); }
    public __Table_Vec_set_attr_t get(__Table_Vec_set_attr_t obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

