// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

public final class __Value {
  private __Value() { }
  public static final byte NONE = 0;
  public static final byte BgpAggregation = 1;
  public static final byte BgpMultipath = 2;
  public static final byte BgpNeighbor = 3;
  public static final byte BgpNetwork = 4;
  public static final byte BgpRedis = 5;
  public static final byte BgpReflectClient = 6;
  public static final byte Fib = 7;
  public static final byte IBgpNeighbor = 8;
  public static final byte Interface = 9;
  public static final byte L3Link = 10;
  public static final byte Node = 11;
  public static final byte OspfIntfSetting = 12;
  public static final byte OspfMultipath = 13;
  public static final byte OspfRedis = 14;
  public static final byte OspfStubArea = 15;
  public static final byte RouteMapIn = 16;
  public static final byte RouteMapOut = 17;
  public static final byte StaticRoute = 18;
  public static final byte Tuple0 = 19;

  public static final String[] names = { "NONE", "BgpAggregation", "BgpMultipath", "BgpNeighbor", "BgpNetwork", "BgpRedis", "BgpReflectClient", "Fib", "IBgpNeighbor", "Interface", "L3Link", "Node", "OspfIntfSetting", "OspfMultipath", "OspfRedis", "OspfStubArea", "RouteMapIn", "RouteMapOut", "StaticRoute", "Tuple0", };

  public static String name(int e) { return names[e]; }
}

