// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CommonPrefix extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static CommonPrefix getRootAsCommonPrefix(ByteBuffer _bb) { return getRootAsCommonPrefix(_bb, new CommonPrefix()); }
  public static CommonPrefix getRootAsCommonPrefix(ByteBuffer _bb, CommonPrefix obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CommonPrefix __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.prefix_t prefix() { return prefix(new ddlog.__routing.prefix_t()); }
  public ddlog.__routing.prefix_t prefix(ddlog.__routing.prefix_t obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createCommonPrefix(FlatBufferBuilder builder,
      int prefixOffset) {
    builder.startTable(1);
    CommonPrefix.addPrefix(builder, prefixOffset);
    return CommonPrefix.endCommonPrefix(builder);
  }

  public static void startCommonPrefix(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addPrefix(FlatBufferBuilder builder, int prefixOffset) { builder.addOffset(0, prefixOffset, 0); }
  public static int endCommonPrefix(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CommonPrefix get(int j) { return get(new CommonPrefix(), j); }
    public CommonPrefix get(CommonPrefix obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

