// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Interface extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Interface getRootAsInterface(ByteBuffer _bb) { return getRootAsInterface(_bb, new Interface()); }
  public static Interface getRootAsInterface(ByteBuffer _bb, Interface obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Interface __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.vnode_t node() { return node(new ddlog.__routing.vnode_t()); }
  public ddlog.__routing.vnode_t node(ddlog.__routing.vnode_t obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String intf() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer intfAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer intfInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public ddlog.__routing.prefix_t prefix() { return prefix(new ddlog.__routing.prefix_t()); }
  public ddlog.__routing.prefix_t prefix(ddlog.__routing.prefix_t obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createInterface(FlatBufferBuilder builder,
      int nodeOffset,
      int intfOffset,
      int prefixOffset) {
    builder.startTable(3);
    Interface.addPrefix(builder, prefixOffset);
    Interface.addIntf(builder, intfOffset);
    Interface.addNode(builder, nodeOffset);
    return Interface.endInterface(builder);
  }

  public static void startInterface(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNode(FlatBufferBuilder builder, int nodeOffset) { builder.addOffset(0, nodeOffset, 0); }
  public static void addIntf(FlatBufferBuilder builder, int intfOffset) { builder.addOffset(1, intfOffset, 0); }
  public static void addPrefix(FlatBufferBuilder builder, int prefixOffset) { builder.addOffset(2, prefixOffset, 0); }
  public static int endInterface(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Interface get(int j) { return get(new Interface(), j); }
    public Interface get(Interface obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

