// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MatchCommunity extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static MatchCommunity getRootAsMatchCommunity(ByteBuffer _bb) { return getRootAsMatchCommunity(_bb, new MatchCommunity()); }
  public static MatchCommunity getRootAsMatchCommunity(ByteBuffer _bb, MatchCommunity obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatchCommunity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.community_t community() { return community(new ddlog.__routing.community_t()); }
  public ddlog.__routing.community_t community(ddlog.__routing.community_t obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMatchCommunity(FlatBufferBuilder builder,
      int communityOffset) {
    builder.startTable(1);
    MatchCommunity.addCommunity(builder, communityOffset);
    return MatchCommunity.endMatchCommunity(builder);
  }

  public static void startMatchCommunity(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addCommunity(FlatBufferBuilder builder, int communityOffset) { builder.addOffset(0, communityOffset, 0); }
  public static int endMatchCommunity(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatchCommunity get(int j) { return get(new MatchCommunity(), j); }
    public MatchCommunity get(MatchCommunity obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

