// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MatchPrefixList extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static MatchPrefixList getRootAsMatchPrefixList(ByteBuffer _bb) { return getRootAsMatchPrefixList(_bb, new MatchPrefixList()); }
  public static MatchPrefixList getRootAsMatchPrefixList(ByteBuffer _bb, MatchPrefixList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatchPrefixList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.__Table_prefix_list_t prefixList(int j) { return prefixList(new ddlog.__routing.__Table_prefix_list_t(), j); }
  public ddlog.__routing.__Table_prefix_list_t prefixList(ddlog.__routing.__Table_prefix_list_t obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int prefixListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ddlog.__routing.__Table_prefix_list_t.Vector prefixListVector() { return prefixListVector(new ddlog.__routing.__Table_prefix_list_t.Vector()); }
  public ddlog.__routing.__Table_prefix_list_t.Vector prefixListVector(ddlog.__routing.__Table_prefix_list_t.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createMatchPrefixList(FlatBufferBuilder builder,
      int prefix_listOffset) {
    builder.startTable(1);
    MatchPrefixList.addPrefixList(builder, prefix_listOffset);
    return MatchPrefixList.endMatchPrefixList(builder);
  }

  public static void startMatchPrefixList(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addPrefixList(FlatBufferBuilder builder, int prefixListOffset) { builder.addOffset(0, prefixListOffset, 0); }
  public static int createPrefixListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPrefixListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMatchPrefixList(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatchPrefixList get(int j) { return get(new MatchPrefixList(), j); }
    public MatchPrefixList get(MatchPrefixList obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

