// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

public final class match_attr_t {
  private match_attr_t() { }
  public static final byte NONE = 0;
  public static final byte MatchNextHopIp = 1;
  public static final byte MatchPrefixList = 2;
  public static final byte MatchAsPath = 3;
  public static final byte MatchCommunity = 4;

  public static final String[] names = { "NONE", "MatchNextHopIp", "MatchPrefixList", "MatchAsPath", "MatchCommunity", };

  public static String name(int e) { return names[e]; }
}

