// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MatchAsPath extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static MatchAsPath getRootAsMatchAsPath(ByteBuffer _bb) { return getRootAsMatchAsPath(_bb, new MatchAsPath()); }
  public static MatchAsPath getRootAsMatchAsPath(ByteBuffer _bb, MatchAsPath obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatchAsPath __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long as_() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createMatchAsPath(FlatBufferBuilder builder,
      long as_) {
    builder.startTable(1);
    MatchAsPath.addAs_(builder, as_);
    return MatchAsPath.endMatchAsPath(builder);
  }

  public static void startMatchAsPath(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addAs_(FlatBufferBuilder builder, long as_) { builder.addLong(0, as_, 0L); }
  public static int endMatchAsPath(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatchAsPath get(int j) { return get(new MatchAsPath(), j); }
    public MatchAsPath get(MatchAsPath obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

