// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OspfRedis extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static OspfRedis getRootAsOspfRedis(ByteBuffer _bb) { return getRootAsOspfRedis(_bb, new OspfRedis()); }
  public static OspfRedis getRootAsOspfRedis(ByteBuffer _bb, OspfRedis obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public OspfRedis __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.vnode_t node() { return node(new ddlog.__routing.vnode_t()); }
  public ddlog.__routing.vnode_t node(ddlog.__routing.vnode_t obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public String protocol() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer protocolAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer protocolInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public long process() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createOspfRedis(FlatBufferBuilder builder,
      int nodeOffset,
      int protocolOffset,
      long process) {
    builder.startTable(3);
    OspfRedis.addProcess(builder, process);
    OspfRedis.addProtocol(builder, protocolOffset);
    OspfRedis.addNode(builder, nodeOffset);
    return OspfRedis.endOspfRedis(builder);
  }

  public static void startOspfRedis(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNode(FlatBufferBuilder builder, int nodeOffset) { builder.addOffset(0, nodeOffset, 0); }
  public static void addProtocol(FlatBufferBuilder builder, int protocolOffset) { builder.addOffset(1, protocolOffset, 0); }
  public static void addProcess(FlatBufferBuilder builder, long process) { builder.addLong(2, process, 0L); }
  public static int endOspfRedis(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public OspfRedis get(int j) { return get(new OspfRedis(), j); }
    public OspfRedis get(OspfRedis obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

