// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OspfMultipath extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static OspfMultipath getRootAsOspfMultipath(ByteBuffer _bb) { return getRootAsOspfMultipath(_bb, new OspfMultipath()); }
  public static OspfMultipath getRootAsOspfMultipath(ByteBuffer _bb, OspfMultipath obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public OspfMultipath __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.vnode_t node() { return node(new ddlog.__routing.vnode_t()); }
  public ddlog.__routing.vnode_t node(ddlog.__routing.vnode_t obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long k() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long process() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createOspfMultipath(FlatBufferBuilder builder,
      int nodeOffset,
      long k,
      long process) {
    builder.startTable(3);
    OspfMultipath.addProcess(builder, process);
    OspfMultipath.addK(builder, k);
    OspfMultipath.addNode(builder, nodeOffset);
    return OspfMultipath.endOspfMultipath(builder);
  }

  public static void startOspfMultipath(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNode(FlatBufferBuilder builder, int nodeOffset) { builder.addOffset(0, nodeOffset, 0); }
  public static void addK(FlatBufferBuilder builder, long k) { builder.addLong(1, k, 0L); }
  public static void addProcess(FlatBufferBuilder builder, long process) { builder.addLong(2, process, 0L); }
  public static int endOspfMultipath(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public OspfMultipath get(int j) { return get(new OspfMultipath(), j); }
    public OspfMultipath get(OspfMultipath obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

