// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

public final class prefix_list_t {
  private prefix_list_t() { }
  public static final byte NONE = 0;
  public static final byte CommonPrefix = 1;
  public static final byte ExtendPrefix = 2;

  public static final String[] names = { "NONE", "CommonPrefix", "ExtendPrefix", };

  public static String name(int e) { return names[e]; }
}

