// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RouteMapIn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static RouteMapIn getRootAsRouteMapIn(ByteBuffer _bb) { return getRootAsRouteMapIn(_bb, new RouteMapIn()); }
  public static RouteMapIn getRootAsRouteMapIn(ByteBuffer _bb, RouteMapIn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RouteMapIn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.vnode_t node() { return node(new ddlog.__routing.vnode_t()); }
  public ddlog.__routing.vnode_t node(ddlog.__routing.vnode_t obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ddlog.__routing.vnode_t fromNode() { return fromNode(new ddlog.__routing.vnode_t()); }
  public ddlog.__routing.vnode_t fromNode(ddlog.__routing.vnode_t obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ddlog.__routing.route_map_t policy(int j) { return policy(new ddlog.__routing.route_map_t(), j); }
  public ddlog.__routing.route_map_t policy(ddlog.__routing.route_map_t obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int policyLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ddlog.__routing.route_map_t.Vector policyVector() { return policyVector(new ddlog.__routing.route_map_t.Vector()); }
  public ddlog.__routing.route_map_t.Vector policyVector(ddlog.__routing.route_map_t.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createRouteMapIn(FlatBufferBuilder builder,
      int nodeOffset,
      int from_nodeOffset,
      int policyOffset) {
    builder.startTable(3);
    RouteMapIn.addPolicy(builder, policyOffset);
    RouteMapIn.addFromNode(builder, from_nodeOffset);
    RouteMapIn.addNode(builder, nodeOffset);
    return RouteMapIn.endRouteMapIn(builder);
  }

  public static void startRouteMapIn(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addNode(FlatBufferBuilder builder, int nodeOffset) { builder.addOffset(0, nodeOffset, 0); }
  public static void addFromNode(FlatBufferBuilder builder, int fromNodeOffset) { builder.addOffset(1, fromNodeOffset, 0); }
  public static void addPolicy(FlatBufferBuilder builder, int policyOffset) { builder.addOffset(2, policyOffset, 0); }
  public static int createPolicyVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPolicyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRouteMapIn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RouteMapIn get(int j) { return get(new RouteMapIn(), j); }
    public RouteMapIn get(RouteMapIn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

