// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

public final class set_attr_t {
  private set_attr_t() { }
  public static final byte NONE = 0;
  public static final byte SetNextHopIp = 1;
  public static final byte SetLocalPref = 2;
  public static final byte SetMed = 3;
  public static final byte SetCommunity = 4;

  public static final String[] names = { "NONE", "SetNextHopIp", "SetLocalPref", "SetMed", "SetCommunity", };

  public static String name(int e) { return names[e]; }
}

