// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SetCommunity extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static SetCommunity getRootAsSetCommunity(ByteBuffer _bb) { return getRootAsSetCommunity(_bb, new SetCommunity()); }
  public static SetCommunity getRootAsSetCommunity(ByteBuffer _bb, SetCommunity obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetCommunity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean additive() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public ddlog.__routing.community_t community() { return community(new ddlog.__routing.community_t()); }
  public ddlog.__routing.community_t community(ddlog.__routing.community_t obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createSetCommunity(FlatBufferBuilder builder,
      boolean additive,
      int communityOffset) {
    builder.startTable(2);
    SetCommunity.addCommunity(builder, communityOffset);
    SetCommunity.addAdditive(builder, additive);
    return SetCommunity.endSetCommunity(builder);
  }

  public static void startSetCommunity(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addAdditive(FlatBufferBuilder builder, boolean additive) { builder.addBoolean(0, additive, false); }
  public static void addCommunity(FlatBufferBuilder builder, int communityOffset) { builder.addOffset(1, communityOffset, 0); }
  public static int endSetCommunity(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetCommunity get(int j) { return get(new SetCommunity(), j); }
    public SetCommunity get(SetCommunity obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

