// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SetLocalPref extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static SetLocalPref getRootAsSetLocalPref(ByteBuffer _bb) { return getRootAsSetLocalPref(_bb, new SetLocalPref()); }
  public static SetLocalPref getRootAsSetLocalPref(ByteBuffer _bb, SetLocalPref obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SetLocalPref __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long localPref() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createSetLocalPref(FlatBufferBuilder builder,
      long local_pref) {
    builder.startTable(1);
    SetLocalPref.addLocalPref(builder, local_pref);
    return SetLocalPref.endSetLocalPref(builder);
  }

  public static void startSetLocalPref(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addLocalPref(FlatBufferBuilder builder, long localPref) { builder.addLong(0, localPref, 0L); }
  public static int endSetLocalPref(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SetLocalPref get(int j) { return get(new SetLocalPref(), j); }
    public SetLocalPref get(SetLocalPref obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

