// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StaticRoute extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static StaticRoute getRootAsStaticRoute(ByteBuffer _bb) { return getRootAsStaticRoute(_bb, new StaticRoute()); }
  public static StaticRoute getRootAsStaticRoute(ByteBuffer _bb, StaticRoute obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StaticRoute __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ddlog.__routing.vnode_t node() { return node(new ddlog.__routing.vnode_t()); }
  public ddlog.__routing.vnode_t node(ddlog.__routing.vnode_t obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ddlog.__routing.prefix_t prefix() { return prefix(new ddlog.__routing.prefix_t()); }
  public ddlog.__routing.prefix_t prefix(ddlog.__routing.prefix_t obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public ddlog.__routing.ip_t nextHopIp() { return nextHopIp(new ddlog.__routing.ip_t()); }
  public ddlog.__routing.ip_t nextHopIp(ddlog.__routing.ip_t obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long adminCost() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createStaticRoute(FlatBufferBuilder builder,
      int nodeOffset,
      int prefixOffset,
      int next_hop_ipOffset,
      long adminCost) {
    builder.startTable(4);
    StaticRoute.addAdminCost(builder, adminCost);
    StaticRoute.addNextHopIp(builder, next_hop_ipOffset);
    StaticRoute.addPrefix(builder, prefixOffset);
    StaticRoute.addNode(builder, nodeOffset);
    return StaticRoute.endStaticRoute(builder);
  }

  public static void startStaticRoute(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addNode(FlatBufferBuilder builder, int nodeOffset) { builder.addOffset(0, nodeOffset, 0); }
  public static void addPrefix(FlatBufferBuilder builder, int prefixOffset) { builder.addOffset(1, prefixOffset, 0); }
  public static void addNextHopIp(FlatBufferBuilder builder, int nextHopIpOffset) { builder.addOffset(2, nextHopIpOffset, 0); }
  public static void addAdminCost(FlatBufferBuilder builder, long adminCost) { builder.addLong(3, adminCost, 0L); }
  public static int endStaticRoute(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StaticRoute get(int j) { return get(new StaticRoute(), j); }
    public StaticRoute get(StaticRoute obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

