// automatically generated by the FlatBuffers compiler, do not modify

package ddlog.__routing;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Tuple0 extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Tuple0 getRootAsTuple0(ByteBuffer _bb) { return getRootAsTuple0(_bb, new Tuple0()); }
  public static Tuple0 getRootAsTuple0(ByteBuffer _bb, Tuple0 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Tuple0 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startTuple0(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endTuple0(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Tuple0 get(int j) { return get(new Tuple0(), j); }
    public Tuple0 get(Tuple0 obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

